sudo mount /dev/sda1 /data/sda
sudo mount /dev/sdb1 /data/sdb
sudo mount /dev/sdc1 /data/sdc
sudo mount /dev/sde1 /data/sdd
sudo mount /dev/sde1 /data/sde
sudo mount /dev/sdf1 /data/sdf
sudo mount /dev/sdg1 /data/sdg
sudo mount /dev/sdh1 /data/sdh
sudo mount /dev/sdi1 /data/sdi
sudo mount /dev/sdj1 /data/sdj
sudo mount /dev/sdk1 /data/sdk
sudo mount /dev/sdl1 /data/sdl
sudo mount /dev/sdm1 /data/sdm
sudo mount /dev/sdn1 /data/sdn
sudo mount /dev/sdo1 /data/sdo
sudo mount /dev/sdp1 /data/sdp
sudo mount /dev/sdq1 /data/sdq
sudo mount /dev/sdr1 /data/sdr
sudo mount /dev/sds1 /data/sds
sudo mount /dev/sdt1 /data/sdt
sudo mount /dev/sdu1 /data/sdu
sudo mount /dev/sdv1 /data/sdv
sudo mount /dev/sdw1 /data/sdw
sudo mount /dev/sdx1 /data/sdx
sudo mount /dev/sdy1 /data/sdy
sudo mount /dev/sdz1 /data/sdz
sudo mount /dev/sdaa1 /data/sdaa
sudo mount /dev/sdab1 /data/sdab
sudo mount /dev/sdac1 /data/sdac
sudo mount /dev/sdad1 /data/sdad
sudo mount /dev/sdae1 /data/sdae
sudo mount /dev/sdaf1 /data/sdaf
sudo mount /dev/sdag1 /data/sdag
sudo mount /dev/sdah1 /data/sdah
sudo mount /dev/sdai1 /data/sdai